### PR TITLE
prep-javascript-loops - Tyler Stahl

### PR DESCRIPTION
**Pull request by TyStahl**
Screenshot prep-javascript-loops

### CODE REVIEW

**Review by BrettAlbright — CHANGES_REQUESTED** [review]
code looks good Tyler, except for one thing, you don't want to use `Array` you would want to use `array` or even a name like `arrayOfNumbers`. The reason is as follows
1. Capital letters are typically reserved for `Object constructors` in JavaScript, so Array, is actually the Array object constructor in JS, and by using `Array` you are overwriting that constructor. 
2. Its best to avoid capital letters at the start of variable names for that reason. 

Its also worth pointing out that good variable names hold semantic connection to the data they contain so `numberArray` for an array of numbers is a good want to go.

**Comment by TyStahl** [comment]
prep-javascript-loops take two

**Comment by TyStahl** [comment]
prep-javascript-loops code

**Review by BrettAlbright — APPROVED** [review]
👍🏼

**Pull request merged**
